language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=./

branches:
  only:
  - deploy
after_success:
 - coveralls
 - coverage report
 
